

services:
  mongo:
    image: mongo:6.0
    container_name: helpdeskpilot-mongo
    ports:
      - "27017:27017"
    volumes:
      - helpdeskpilot-mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: helpdeskpilot
    restart: unless-stopped

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: helpdeskpilot-api
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/helpdeskpilot
      - PORT=8080
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongo
    restart: unless-stopped

  seed:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=mongodb://mongo:27017/helpdeskpilot
    volumes:
      - ./backend:/app
    command: npm run seed
    depends_on:
      - mongo

volumes:
  helpdeskpilot-mongo-data: